export const ALIASES: Record<string, string> = {
  "10no pole": "10 no pole",
  "4no bridge": "4 no bridge",
  "58-gate": "58 gate",
  "8b": "jadavpur 8b",
  "8no kalibari": "8 no kalibari",
  "airport 1": "airport gate 1",
  "airport 1 no gate": "airport gate 1",
  "airport 1no": "airport gate 1",
  "airport 2 no gate": "airport gate 2",
  "airport 3": "airport gate 3",
  "airport 3 gate": "airport gate 3",
  "airport 3 no gate": "airport gate 3",
  "airport 3no": "airport gate 3",
  "airport 3no gate": "airport gate 3",
  "airport gate 2 5": "airport gate 2.5",
  "airport gate no 1": "airport gate 1",
  "airport gate no 2": "airport gate 2",
  "airport gate no 2 5": "airport gate 2.5",
  "airport gate no 3": "airport gate 3",
  "airport gate-1": "airport gate 1",
  "airport gate-3": "airport gate 3",
  "b b d bag": "bbd bag",
  "ballygunge s t n": "ballygunge station",
  "ballygunge stn": "ballygunge station",
  "baranagar metro": "dunlop",
  "barasat champadali": "barasat chapadali",
  "barasat dak bunglow": "barasat dakbunglow",
  "baruipur fultala central terminus": "baruipur fultala",
  "behala 14": "behala 14 no",
  "behala 14no": "behala 14 no",
  "belgachia metro": "belgachia",
  "bongaon 1no railgate bazar": "bongaon 1 no railgate bazar",
  "botanic garden": "b garden",
  "botanical garden": "b garden",
  "bridge 4": "4 no bridge",
  "bridge no 4": "4 no bridge",
  "building": "beleghata building",
  "central metro": "central",
  "chandni": "chandni chowk",
  "chandni market": "chandni chowk",
  "cit": "beleghata cit",
  "city center": "city center 1",
  "city center-1": "city center 1",
  "city center-2": "city center 2",
  "city centre": "city center 1",
  "city centre 1": "city center 1",
  "city centre 2": "city center 2",
  "college": "college more",
  "dalhousie": "bbd bag",
  "dlf 1": "dlf1",
  "dlf 2": "dlf2",
  "dlf1": "dlf1",
  "dlf2": "dlf2",
  "durgapur city centre": "durgapur city center",
  "esplanade l20": "esplanade",
  "gitanjali": "naktala",
  "howrah": "howrah station",
  "howrah stn": "howrah station",
  "hudco": "ultadanga hudco",
  "id hospital": "beleghata id hospital",
  "mahanayak uttam kumar": "tollygunge metro",
  "mahatma gandhi road": "mg road",
  "maidan metro": "maidan",
  "masterda surya sen": "bansdroni",
  "mg road metro": "mg road",
  "netaji": "kudghat",
  "r g kar": "rg kar",
  "rg kar hospital": "rg kar",
  "ruby hospital": "ruby",
  "sales tax": "beleghata sales tax",
  "saltlake karunamoyee": "karunamoyee",
  "saltlake sector v": "sector v",
  "santragachi bus terminal": "santragachi bus terminus",
  "sealdah station": "sealdah",
  "sealdah stn": "sealdah",
  "sec v": "sector v",
  "sector v saltlake": "sector v",
  "shapooji housing": "shapoorji",
  "shapoorji housing": "shapoorji",
  "shyambazar 5 point": "shyambazar",
  "sovabazar metro": "sovabazar",
  "sovabazar sutanuti": "sovabazar",
  "sukho brishti": "shapoorji",
  "sukhobrishti": "shapoorji",
  "unitech gate no 1": "unitech gate 1"
} as const;
