export const SPELLING: Record<string, string> = {
  "a p c": "apc",
  "a p c college": "apc college",
  "ajoynagar": "ajaynagar",
  "akankha": "akanksha",
  "akansha": "akanksha",
  "alipur": "alipore",
  "anwar sha connector": "prince anwar shah connector",
  "anwarsah road": "anwar shah road",
  "ashok nagar": "ashoknagar",
  "ashokenagar": "ashoknagar",
  "ashoknaga": "ashoknagar",
  "b e college": "be college",
  "b k paul": "bk paul",
  "b t": "bt",
  "b t college": "bt college",
  "baguihati": "baguiati",
  "baishnabghata": "baisnabghata",
  "bajar": "bazar",
  "bakshara": "baksara",
  "bakul tala": "bakultala",
  "bally ghat": "ballyghat",
  "bally halt": "ballyhalt",
  "ballygaunj": "ballygunge",
  "ballygunj": "ballygunge",
  "bamangachhi": "bamangachi",
  "bashirhat": "basirhat",
  "bazer": "bazar",
  "beckbagan": "beck bagan",
  "bekbagan": "beck bagan",
  "belepol": "belepole",
  "belgacchia": "belgachia",
  "belgachhia": "belgachia",
  "belghoria": "belgharia",
  "beliaghata": "beleghata",
  "bhaban": "bhawan",
  "bhawani bhawan": "bhabani bhawan",
  "bhawanipore": "bhowanipore",
  "bhawanipur": "bhowanipore",
  "bhowanipur": "bhowanipore",
  "bhyabla halt": "bhyablahalt",
  "bichali ghar": "bichali ghat",
  "bidhan nagar college": "bidhannagar college",
  "bonhoogly": "bonhooghly",
  "borali ghat": "boralighat",
  "bow bazar": "bowbazar",
  "burra bazar": "barabazar",
  "burrabazar": "barabazar",
  "c a island": "ca island",
  "c i t road": "cit road",
  "chadni": "chandni",
  "champadali": "chapadali",
  "chinarpark": "chinar park",
  "chingrihata": "chingrighata",
  "chiriamore": "chiria more",
  "d l f": "dlf",
  "dakshineshwar": "dakshineswar",
  "das nagar": "dasnagar",
  "desapriya park": "deshapriya park",
  "deshoprio park": "deshapriya park",
  "dhruba bazar": "dhrubabazar",
  "dhulor bandh": "dhulorbandh",
  "doltola": "doltala",
  "dum dum": "dumdum",
  "dutta pukur": "duttapukur",
  "e m bypass": "em bypass",
  "eco park": "ecopark",
  "eco space": "ecospace",
  "girishpark": "girish park",
  "gobindopur": "gobindapur",
  "golfgreen": "golf green",
  "haldiram": "haldirams",
  "hela battala": "helabattala",
  "highland park": "hiland park",
  "home town": "hometown",
  "jadavpur p s": "jadavpur ps",
  "jadavpur thana": "jadavpur ps",
  "japanigate": "japani gate",
  "jinjira": "jhinjhira",
  "joygacchi": "joygachi",
  "joygachhi": "joygachi",
  "kadambagacchi": "kadambagachi",
  "kali park": "kalipark",
  "kazi bari": "kazibari",
  "keshtopur": "kestopur",
  "khardah": "khardaha",
  "khashmallik": "khasmallick",
  "khidderpore": "kidderpore",
  "khiderpore": "kidderpore",
  "khiderpur": "kidderpore",
  "khidirpur": "kidderpore",
  "kidderpur": "kidderpore",
  "lake town": "laketown",
  "lal bazar": "lalbazar",
  "lal kuthi": "lalkuthi",
  "m g road": "mg road",
  "mahisbatan": "mahishbathan",
  "mahisbathan": "mahishbathan",
  "majerhat": "majherhat",
  "mallickbazar": "mallick bazar",
  "mallikbazar": "mallick bazar",
  "malncha": "malancha",
  "manicktala": "maniktala",
  "michael nagar": "michaelnagar",
  "mollargate": "mollar gate",
  "mominpur": "mominpore",
  "moulai": "moulali",
  "mullickbazar": "mallick bazar",
  "murarishah": "murarisha",
  "nababpur": "nawabpur",
  "nagerbazar": "nager bazar",
  "najrul": "nazrul",
  "narkel bagan": "narkelbagan",
  "natun rastar": "natun rasta",
  "new barrack pore": "new barrackpore",
  "new town": "newtown",
  "notun rastar": "natun rasta",
  "p a sha connector": "prince anwar shah connector",
  "p a sha road": "anwar shah road",
  "p a shah road": "anwar shah road",
  "p g hospital": "pg hospital",
  "p n b": "pnb",
  "p t s": "pts",
  "pa shah road": "anwar shah road",
  "parnashree": "parnasree",
  "phillips": "philips",
  "prafulla nagar": "prafullanagar",
  "pramod nagar": "pramodnagar",
  "r n chowdhury road": "rn chowdhury road",
  "rabindrasadan": "rabindra sadan",
  "rabinrasadan": "rabindra sadan",
  "rajabajar": "rajabazar",
  "ramnarayanpurramnarayanpur": "ramnarayanpur",
  "rasbehari": "rashbehari",
  "rashbihari": "rashbehari",
  "s d f": "sdf",
  "s m nagar": "sm nagar",
  "safuipara": "sapuipara",
  "sakherbazar": "sakher bazar",
  "sakherbzar": "sakher bazar",
  "salt lake": "saltlake",
  "saltlake c a block": "saltlake ca block",
  "santragachhi": "santragachi",
  "sarkar bazar": "sarkarbazar",
  "sarobar": "sarovar",
  "sevasram": "sevashram",
  "shirakhole": "shirakole",
  "shirakol": "shirakole",
  "shishu": "sishu",
  "shishumangal": "sishu mangal",
  "shobhabazar": "sovabazar",
  "shreebhumi": "sreebhumi",
  "silpara": "shilpara",
  "sinthee": "sinthi",
  "sobhabazar": "sovabazar",
  "sodpur": "sodepur",
  "sova bajar": "sovabazar",
  "sova bazar": "sovabazar",
  "subhasnagar": "subhash nagar",
  "sukanta nagar": "sukantanagar",
  "susrut": "sushrut",
  "techonopolis": "technopolis",
  "tegharia": "teghoria",
  "tollygunj": "tollygunge",
  "udainarayanpur": "udaynarayanpur",
  "udanarayanpur": "udaynarayanpur",
  "udaynaryanpur": "udaynarayanpur",
  "ukiler hat": "ukilerhat",
  "ultodanga": "ultadanga",
  "uttar panchannangram": "uttar panchannagram",
  "v i p": "vip",
  "vandergachha": "vandergacha",
  "w i p r o": "wipro"
} as const;
